user www-data;
worker_processes auto;
error_log stderr;
pid /run/nginx.pid;

include /etc/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    map $http_x_forwarded_host $qgis_host {
        "~(?<h>[^:]+)" $h;
        default $host;
    }

    map $http_host $port {
        "~*.*:(?<p>.*)" $p;
        default $server_port;
    }

    map $http_x_forwarded_proto $qgis_ssl {
        "https" "on";
        default $https;
    }

    map $http_x_forwarded_port $qgis_port {
        "" $port;
        default $http_x_forwarded_port;
    }

    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name _;
        root /usr/share/nginx/html;

        location /ogcapi/ {
            fastcgi_pass localhost:9993;
            fastcgi_param SCRIPT_FILENAME /usr/lib/cgi-bin/qgis_mapserv.fcgi;
            fastcgi_param QUERY_STRING $query_string;
            fastcgi_param HTTPS $qgis_ssl;
            fastcgi_param SERVER_NAME $qgis_host;
            fastcgi_param SERVER_PORT $qgis_port;
            include fastcgi_params;
        }

        location /wfs3/ {
            fastcgi_pass localhost:9993;
            fastcgi_param SCRIPT_FILENAME /usr/lib/cgi-bin/qgis_mapserv.fcgi;
            fastcgi_param QUERY_STRING $query_string;
            fastcgi_param HTTPS $qgis_ssl;
            fastcgi_param SERVER_NAME $qgis_host;
            fastcgi_param SERVER_PORT $qgis_port;
            include fastcgi_params;
        }

        location /ows/ {
            rewrite ^/ows/$ /qgis/qgis_mapserv.fcgi;
        }

        location /qgis/ {
            internal;
            root /var/www/data;
            fastcgi_pass localhost:9993;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param QUERY_STRING $query_string;
            fastcgi_param HTTPS $qgis_ssl;
            fastcgi_param SERVER_NAME $qgis_host;
            fastcgi_param SERVER_PORT $qgis_port;
            include fastcgi_params;
        }
    }
}
